sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:

- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile ./assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg

script:
if [ $TRAVIS_BRANCH == "feature" ]; then 
- sfdx force:source:deploy -c -u HubOrg -p force-app -w -1 -l RunAllTestsInOrg; 
fi

if [ $TRAVIS_BRANCH == "master" ]; then 
- sfdx force:source:deploy -u HubOrg -p force-app; 
fi

